"""licensing.py

Standalone licensing module for Python/Tkinter desktop applications.

Security model (high-level):
- A license payload is generated by an admin/offline process.
- The payload contains machine ID, expiry timestamp, and license type.
- A HMAC-SHA256 signature protects integrity/authenticity of payload.
- The final activation key is URL-safe base64 encoded JSON.
- Client-side validation checks format, signature, machine binding, and expiry.

IMPORTANT:
- The secret key is embedded in this module to satisfy the requirement for a
  self-contained implementation. In production, treat this key as sensitive and
  rotate it if leaked.
"""

from __future__ import annotations

import base64
import datetime as dt
import hashlib
import hmac
import json
import os
import platform
import socket
import sys
import uuid
from pathlib import Path
from typing import Any, Dict, Optional, Tuple


# -----------------------------------------------------------------------------
# Configuration
# -----------------------------------------------------------------------------

# Replace with your own strong random bytes before shipping.
# Keeping it in-module is convenient but less secure than server-side signing.
_SECRET_KEY = b"TradingAi-Standalone-Licensing-Secret-v1-ChangeMe"

# Default location for a saved license file.
DEFAULT_LICENSE_PATH = Path("license.key")

# ISO-8601 format used for expiry timestamp.
ISO_FORMAT = "%Y-%m-%dT%H:%M:%SZ"


# -----------------------------------------------------------------------------
# Exceptions
# -----------------------------------------------------------------------------

class LicenseError(Exception):
    """Base class for all licensing related errors."""


class InvalidKeyFormatError(LicenseError):
    """Raised when activation key cannot be decoded/parsing fails."""


class WrongMachineError(LicenseError):
    """Raised when license machine_id does not match current device."""


class TamperedSignatureError(LicenseError):
    """Raised when HMAC signature check fails (data likely modified)."""


class ExpiredLicenseError(LicenseError):
    """Raised when license has passed its expiry timestamp."""


# -----------------------------------------------------------------------------
# Internal helpers
# -----------------------------------------------------------------------------


def _utc_now() -> dt.datetime:
    """Return timezone-naive UTC now for consistent comparisons/serialization."""
    return dt.datetime.utcnow()



def _build_signing_payload(machine_id: str, expires_at: str, license_type: str) -> bytes:
    """Build canonical bytes for HMAC signing/validation.

    Ordering and separators are fixed so both generator and validator produce
    identical bytes for the same logical payload.
    """
    data = {
        "machine_id": machine_id,
        "expires_at": expires_at,
        "type": license_type,
    }
    canonical = json.dumps(data, separators=(",", ":"), sort_keys=True)
    return canonical.encode("utf-8")



def _sign(machine_id: str, expires_at: str, license_type: str) -> str:
    """Create hex HMAC-SHA256 signature for license core fields."""
    payload = _build_signing_payload(machine_id, expires_at, license_type)
    mac = hmac.new(_SECRET_KEY, payload, hashlib.sha256)
    return mac.hexdigest()



def _encode_key(payload: Dict[str, Any]) -> str:
    """Serialize payload to URL-safe base64 string."""
    raw = json.dumps(payload, separators=(",", ":"), sort_keys=True).encode("utf-8")
    return base64.urlsafe_b64encode(raw).decode("ascii")



def _decode_key(activation_key: str) -> Dict[str, Any]:
    """Decode base64 activation key into dict.

    Raises:
        InvalidKeyFormatError: if decode or JSON parsing fails.
    """
    try:
        key = activation_key.strip()
        # Restore missing padding if removed by copy/paste.
        padding = "=" * (-len(key) % 4)
        raw = base64.urlsafe_b64decode((key + padding).encode("ascii"))
        payload = json.loads(raw.decode("utf-8"))
    except Exception as exc:  # safe broad catch to wrap parsing failures
        raise InvalidKeyFormatError("invalid key format: could not decode base64 JSON") from exc

    required = {"machine_id", "expires_at", "type", "signature"}
    if not isinstance(payload, dict) or not required.issubset(payload.keys()):
        raise InvalidKeyFormatError("invalid key format: missing required fields")

    return payload


# -----------------------------------------------------------------------------
# Public API required by prompt
# -----------------------------------------------------------------------------


def generate_machine_id() -> str:
    """Generate a deterministic machine-specific ID.

    The ID is derived from a stable set of system identifiers and then SHA256
    hashed so raw system values are not stored directly in the license.

    Returns:
        str: Hex digest machine fingerprint.
    """
    node = uuid.getnode()  # hardware MAC-derived int when available
    system_info = {
        "platform": platform.platform(),
        "machine": platform.machine(),
        "processor": platform.processor(),
        "hostname": socket.gethostname(),
        "node": str(node),
    }
    canonical = json.dumps(system_info, separators=(",", ":"), sort_keys=True)
    return hashlib.sha256(canonical.encode("utf-8")).hexdigest()



def create_activation_key(days: int, license_type: str, machine_id: Optional[str] = None) -> str:
    """Create an activation key for a machine.

    This function supports offline/admin generation as requested.

    Args:
        days: Number of days license should remain valid from now.
        license_type: Label such as "trial", "pro", "enterprise".
        machine_id: Optional explicit machine_id. If omitted, local machine ID.

    Returns:
        str: Base64-encoded JSON activation key.
    """
    if days <= 0:
        raise ValueError("days must be a positive integer")
    if not license_type or not license_type.strip():
        raise ValueError("license_type must be a non-empty string")

    mid = machine_id or generate_machine_id()
    expires = (_utc_now() + dt.timedelta(days=days)).strftime(ISO_FORMAT)
    signature = _sign(mid, expires, license_type)

    payload = {
        "machine_id": mid,
        "expires_at": expires,
        "type": license_type,
        "signature": signature,
    }
    return _encode_key(payload)



def save_activation_key_file(activation_key: str, path: os.PathLike[str] | str = DEFAULT_LICENSE_PATH) -> Path:
    """Save an activation key string to disk.

    Args:
        activation_key: Encoded license key string.
        path: Output file path.

    Returns:
        Path: The path written.
    """
    output = Path(path)
    output.write_text(activation_key.strip(), encoding="utf-8")
    return output



def load_license_file(path: os.PathLike[str] | str = DEFAULT_LICENSE_PATH) -> str:
    """Load activation key from file.

    Returns:
        str: Raw activation key.

    Raises:
        FileNotFoundError: If license file does not exist.
        InvalidKeyFormatError: If file exists but is empty.
    """
    p = Path(path)
    if not p.exists():
        raise FileNotFoundError(f"license file not found: {p}")

    content = p.read_text(encoding="utf-8").strip()
    if not content:
        raise InvalidKeyFormatError("invalid key format: license file is empty")
    return content



def validate_license(activation_key: str, expected_machine_id: Optional[str] = None) -> Dict[str, Any]:
    """Validate a license key and return decoded payload if valid.

    Validation order:
    1) Decode and parse key format.
    2) Verify HMAC signature (tamper detection).
    3) Ensure machine binding matches current/expected machine.
    4) Ensure license has not expired.

    Args:
        activation_key: Base64-encoded activation key.
        expected_machine_id: Optional target machine ID. Defaults local machine.

    Returns:
        dict: Decoded license payload.

    Raises:
        InvalidKeyFormatError, TamperedSignatureError, WrongMachineError,
        ExpiredLicenseError
    """
    payload = _decode_key(activation_key)

    machine_id = str(payload.get("machine_id"))
    expires_at = str(payload.get("expires_at"))
    license_type = str(payload.get("type"))
    provided_sig = str(payload.get("signature"))

    expected_sig = _sign(machine_id, expires_at, license_type)
    if not hmac.compare_digest(provided_sig, expected_sig):
        raise TamperedSignatureError("tampered signature: license data was modified or forged")

    target_machine = expected_machine_id or generate_machine_id()
    if machine_id != target_machine:
        raise WrongMachineError("wrong machine: this license does not belong to this device")

    try:
        expires_dt = dt.datetime.strptime(expires_at, ISO_FORMAT)
    except ValueError as exc:
        raise InvalidKeyFormatError("invalid key format: expires_at must be UTC ISO format") from exc

    if _utc_now() > expires_dt:
        raise ExpiredLicenseError("expired license: renewal required")

    return payload



def is_license_active(activation_key: str, expected_machine_id: Optional[str] = None) -> Tuple[bool, str]:
    """Convenience wrapper returning `(active, message)`.

    This is useful for UI code (Tkinter) where user-friendly status text is
    often preferred over exception handling in widgets/events.
    """
    try:
        payload = validate_license(activation_key, expected_machine_id=expected_machine_id)
        return True, f"license active ({payload['type']}) until {payload['expires_at']}"
    except LicenseError as exc:
        return False, str(exc)


# -----------------------------------------------------------------------------
# Script / CLI usage for quick testing
# -----------------------------------------------------------------------------


def _print_usage() -> None:
    print(
        "Usage:\n"
        "  python licensing.py machine_id\n"
        "  python licensing.py generate_key [days] [license_type]\n"
        "  python licensing.py activate <activation_key> [license_file]\n"
        "  python licensing.py check [license_file]\n"
    )



def _cli(argv: list[str]) -> int:
    if len(argv) < 2:
        _print_usage()
        return 1

    command = argv[1].lower()

    if command == "machine_id":
        print(generate_machine_id())
        return 0

    if command == "generate_key":
        days = int(argv[2]) if len(argv) > 2 else 30
        license_type = argv[3] if len(argv) > 3 else "trial"
        key = create_activation_key(days=days, license_type=license_type)
        print(key)
        return 0

    if command == "activate":
        if len(argv) < 3:
            print("Error: missing activation key")
            _print_usage()
            return 1
        key = argv[2]
        file_path = argv[3] if len(argv) > 3 else str(DEFAULT_LICENSE_PATH)
        try:
            validate_license(key)
            saved = save_activation_key_file(key, file_path)
            print(f"License activated and saved to: {saved}")
            return 0
        except LicenseError as exc:
            print(f"Activation failed: {exc}")
            return 2

    if command == "check":
        file_path = argv[2] if len(argv) > 2 else str(DEFAULT_LICENSE_PATH)
        try:
            key = load_license_file(file_path)
            active, message = is_license_active(key)
            print(message)
            return 0 if active else 3
        except Exception as exc:
            print(f"Check failed: {exc}")
            return 4

    print(f"Unknown command: {command}")
    _print_usage()
    return 1


if __name__ == "__main__":
    # CLI mode for testing (e.g., `python licensing.py generate_key`).
    if len(sys.argv) > 1:
        raise SystemExit(_cli(sys.argv))

    # Example usage for quick manual verification when no CLI args are supplied.
    # 1) print machine ID
    print(f"Machine ID: {generate_machine_id()}")

    # 2) generate then activate from key string
    sample_key = create_activation_key(days=7, license_type="trial")
    print(f"Sample key: {sample_key}")

    # 3) check if active
    ok, status = is_license_active(sample_key)
    print(f"Active? {ok} | {status}")
